name: Deploy to Dokku (DEV)

# Controls when the workflow will run ---
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: 
      - release/*
  
  pull_request:
    branches: 
      - develop

permissions:
  contents: read

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Cloning repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Push to dokku
          uses: dokku/github-action@master
          with:
            branch: ${{ github.ref_name }}
            git_remote_url: ssh://dokku@m4rc310.com.br/dev-api-persona
            ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}

        - name: Add Dokku host to known_hosts
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H "m4rc310.com.br,159.112.177.194" >> ~/.ssh/known_hosts

        # - name: Deploy to Dokku - v1
        #   env:
        #     DOKKU_HOST: m4rc310.com.br
        #     DOKKU_APP: dev-api-persona
        #     DOKKU_USER: dokku
        #     SSH_PRIVATE_KEY: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
        #   run: |
        #     ssh-agent bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\") && git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP && git push --force dokku ${{ github.ref_name }}"

#        - name: Config CORS
#          run: | 
#            ssh -o StrictHostKeyChecking=no dokku@m4rc310.com.br 'bash ~/scripts/post-deploy'