name: Deploy to Dokku (DEV)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: 
      - "release/*"
  
  pull_request:
    branches: 
      - "develop"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh

      - name: Add Dokku host to known_hosts
        run: |
          ssh-keyscan -H "159.112.177.194" >> ~/.ssh/known_hosts

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: ${{ github.ref_name }}
          git_remote_url: ssh://dokku@159.112.177.194/dev-api-persona
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Dokku
        env:
          DOKKU_HOST: m4rc310.com.br
          DOKKU_APP: dev-api-persona
          DOKKU_USER: dokku
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh-agent bash -c "ssh-add <(echo \"$SSH_PRIVATE_KEY\") && git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP && git push dokku ${{ github.ref_name }}"